"""
Agent 4: Thinker — Generate research ideas from accumulated knowledge.
"""

import logging
import re
from datetime import date

from agents.config import (
    MAX_TOKENS_THINKER, PROMPTS_DIR, MAPS_DIR, IDEAS_DIR, CARDS_DIR, get_client, get_model,
)
from agents.reader import strip_llm_preamble

logger = logging.getLogger("thinker")


def load_prompt() -> str:
    return (PROMPTS_DIR / "thinker.txt").read_text()


def read_file_safe(path) -> str:
    if path.exists():
        return path.read_text().strip()
    return "(empty)"


def get_recent_high_cards(n: int = 10) -> str:
    """Read the most recent card files (proxy for high-scoring)."""
    card_files = sorted(CARDS_DIR.glob("w*.md"), reverse=True)[:n]
    parts = []
    for f in card_files:
        parts.append(f.read_text().strip())
    return "\n\n---\n\n".join(parts) if parts else "(no cards yet)"


def build_idea_index(idea_bank_text: str) -> str:
    """Extract just idea titles and statuses for dedup context."""
    lines = []
    for line in idea_bank_text.split("\n"):
        if line.startswith("## IDEA-"):
            lines.append(line)
        elif "**Status:**" in line:
            lines.append(line)
        elif line.startswith("**Pitch:**") or line.startswith("**Research Question:**"):
            lines.append(line[:150])  # First 150 chars of pitch
    return "\n".join(lines)


def get_next_idea_number() -> int:
    """Parse existing idea bank to find the next idea number."""
    idea_bank = IDEAS_DIR / "idea_bank.md"
    if not idea_bank.exists():
        return 1
    content = idea_bank.read_text()
    numbers = re.findall(r"IDEA-\d{4}-(\d{3})", content)
    if numbers:
        return max(int(n) for n in numbers) + 1
    return 1


def run() -> dict:
    """Run Thinker to generate new ideas. Returns summary stats."""
    # Check if maps have content (Linker must have run)
    landscape = read_file_safe(MAPS_DIR / "research_landscape.md")
    if landscape == "(empty)" or len(landscape) < 100:
        logger.info("Research landscape is empty. Run Linker first.")
        return {"ideas_generated": 0, "reason": "no_maps"}

    client = get_client("thinker")
    model = get_model("thinker")
    system_prompt = load_prompt()

    # Build context
    from agents.profile import load_profile
    profile = load_profile()

    frontier_gaps = read_file_safe(MAPS_DIR / "frontier_gaps.md")
    method_registry = read_file_safe(MAPS_DIR / "method_registry.md")
    current_ideas_full = read_file_safe(IDEAS_DIR / "idea_bank.md")
    current_ideas = build_idea_index(current_ideas_full)
    recent_cards = get_recent_high_cards(10)

    # Load today's digest if available
    from agents.config import KNOWLEDGE_BASE
    digests_dir = KNOWLEDGE_BASE / "digests"
    today = date.today().isoformat()
    digest = read_file_safe(digests_dir / f"{today}.md")

    next_num = get_next_idea_number()

    user_message = (
        f"Today's date: {today}\n"
        f"Next idea number: {next_num} (format as IDEA-{date.today().year}-{next_num:03d})\n\n"
        f"## Researcher Profile\n{profile}\n\n"
        f"## Today's Literature Digest\n{digest}\n\n"
        f"## Research Landscape\n{landscape}\n\n"
        f"## Frontier Gaps\n{frontier_gaps}\n\n"
        f"## Method Registry\n{method_registry}\n\n"
        f"## Recent High-Scoring Cards\n{recent_cards}\n\n"
        f"## Current Idea Bank (avoid duplicates)\n{current_ideas}"
    )

    # Truncate if needed
    if len(user_message) > 100000:
        user_message = user_message[:100000] + "\n[TRUNCATED]"

    try:
        response = client.messages.create(
            model=model,
            max_tokens=MAX_TOKENS_THINKER,
            system=system_prompt,
            messages=[{"role": "user", "content": user_message}],
        )
        raw = response.content[0].text.strip()
    except Exception as e:
        logger.error(f"Thinker API error: {e}")
        return {"ideas_generated": 0, "error": str(e)}

    # Strip LLM preamble before saving
    raw = strip_llm_preamble(raw)

    # Count ideas generated
    ideas_count = len(re.findall(r"## IDEA-", raw))

    # Append to idea bank
    idea_bank = IDEAS_DIR / "idea_bank.md"
    if idea_bank.exists():
        existing = idea_bank.read_text()
    else:
        existing = "# Research Idea Bank\n\n*Generated by the Thinker agent. Evaluated by the Critic agent.*\n\n---\n"

    idea_bank.write_text(existing.rstrip() + "\n\n" + raw + "\n")

    result = {"ideas_generated": ideas_count}
    logger.info(f"Thinker done: generated {ideas_count} ideas")
    
    # Rate limiting: 5s pause after Thinker to avoid API hammering
    import time
    time.sleep(5)
    
    return result


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(name)s] %(message)s")
    from agents.config import ensure_dirs
    ensure_dirs()
    run()
